name: CI CD 
on: [push, workflow_dispatch]
jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: install deps
        run: npm install


  StagingDeployBackend:
    name: Deploy app to heroku
    if: github.event.ref == 'refs/heads/main'
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          buildpack: "https://github.com/lstoll/heroku-buildpack-monorepo"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pram-955-aug-18"
          heroku_email: "pramod.luffy@gmail.com"
    environment:
      name: Staging